# Generated by Django 4.1.7 on 2023-02-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customercredit_customer_credited_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercredit',
            name='price',
        ),
    ]
