# Generated by Django 4.1.7 on 2023-02-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
